---
Name: sendthis-routes
After:
  - 'framework/*'
  - 'cms/*'
---
Director:
  rules:
    'email-subscriptions//$Action/$Email': 'Milkyway\SS\SendThis\Controllers\EmailSubscriptions'
    'mailer/m': 'Milkyway\SS\SendThis\Controllers\Mandrill'
    'mailer/a': 'Milkyway\SS\SendThis\Controllers\AmazonSes'
    'mailer/s': 'Milkyway\SS\SendThis\Controllers\SendGrid'
    'mailer/g': 'Milkyway\SS\SendThis\Controllers\Mailgun'
    'mailer/p': 'Milkyway\SS\SendThis\Controllers\SparkPost'
    '$Slug/mail-footer.gif': 'Milkyway\SS\SendThis\Controllers\Tracker'
