---
Name: send-this--settings
---
SendThis:
  transports:
    default:
      driver: default

  drivers:
    default:
      class: 'Milkyway\SS\SendThis\Transports\Mail'
    smtp:
      class: 'Milkyway\SS\SendThis\Transports\SMTP'
    ses:
      class: 'Milkyway\SS\SendThis\Transports\AmazonSES'
    mandrill:
      class: 'Milkyway\SS\SendThis\Transports\Mandrill'
    sendgrid:
      class: 'Milkyway\SS\SendThis\Transports\SendGrid'
    mailgun:
      class: 'Milkyway\SS\SendThis\Transports\Mailgun'
    sparkpost:
      class: 'Milkyway\SS\SendThis\Transports\SparkPost'

  logging: true
  api_tracking: true
  from_same_domain_only: false
  blacklist_after_bounced: 2
